### ISSUE TITLE
Creación de espacio para contenido de la comunidad

### ISSUE THREAD

**Issue by nelruk** [agendadigitalpy/web-python#10]
El sitio web actualmente cuenta con la documentación orientada a informar al público. No obstante, la creación de contenido por parte de la comunidad puede ser promovida mediante la apertura de un espacio para insertar entradas/páginas.

Se recomienda iniciar esta sección con la publicación de la encuesta y luego abrir el espacio a la comunidad para que pueda entregar sus contenidos propios. Se deberá analizar si será mejor abrir dentro del sitio ya realizado. Si el UI no cuenta con una curva de aprendizaje rápida, la sugerencia es migrar a un CMS con UI más _amigable_ para los _no-técnicos_.

**Comment by matiasinsaurralde** [comment]
Si es para publicar algo como posts, opino que es mejor integrar Medium nomás y enlazamos desde el sitio o ponemos algún subdominio, más fácil, menos mantenimiento, etc.
